language: cpp
dist: trusty
python: '3.6'
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - xorg-dev
      - libgl1-mesa-dev

git:
  submodules: false

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt59base qt59charts-no-lgpl qt59svg
  - source /opt/qt59/bin/qt59-env.sh;
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script:
 - export CC=gcc-7 ;
 - export CXX=g++-7 ;
 - mkdir build && cd build && cmake .. -DPYBIND11_PYTHON_VERSION=3.6 -DBUILD_QC=OFF -DPYTHON_BINDINGS=OFF -DBUILD_EXAMPLES=OFF && cmake --build .
 - cd ../packaging/appimage
 - ./make_appimage.sh
 - ./upload.sh ./qppcad-x86_64.AppImage
